---
title: "Daily 08"
author: "Devina Garcia"
date: "8/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval = FALSE}
https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv
```


```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)

url = 'https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv'

covid = read_csv(url)

```

```{r}

library(zoo)
library(knitr)
library(kableExtra)
library(ggthemes)


```

```{r}
state.of.interest = "California"

covid %>%
  filter(state == state.of.interest) %>%
  group_by(date) %>%
  summarise(cases = sum(cases)) %>%
  mutate(Newcases = cases - lag(cases),
         roll7 = rollmean(Newcases, 7, fill = NA, align="right")) %>%
ggplot(aes(x = date)) +
  geom_col(aes(y = Newcases), col = NA, fill = "#F5B8B5") +
  geom_line(aes(y = roll7), col = "darkred", size = 1) +
  ggthemes::theme_wsj() +
  labs(title = paste("New Reported Cases by Day in", state.of.interest)) +
  labs(subtitle = "Data: NY Times") +
  labs(caption = "Daily Exercise 08") +
  labs(x = "Date", y = "New Cases") +
  theme(plot.background = element_rect(fill = "white"),
        panel.background = element_rect(fill = "white"),
        plot.title = element_text(size = 14, face = 'bold')) +
  theme(aspect.ratio = .5) +
  scale_x_date(date_breaks = "1 month", date_labels = "%b-%y")
          
```

```{r}
dat = covid %>%
  filter(state == "California") %>%
  group_by(county) %>%
  mutate(Newcases = cases - lag(cases)) %>%
  ungroup() %>%
  filter(date == max(date))

(most_new_cases = dat %>%
    slice_max(Newcases, n = 5) %>%
    select(county, Newcases))

knitr::kable(most_new_cases, caption = "New Cases in California Counties",
             col.names = c("County", "New Cases"),
             format.args = list(big.mark = ",")) %>%
kableExtra::kable_styling("striped", full_width = TRUE, font_size = 14)
```

